window.MedEasyProducts = {
  'paracetamol-500mg': {
    name: 'Paracetamol 500mg',
    generic: 'Acetaminophen',
    manufacturer: 'Sun Pharma Laboratories',
    price: '₹267.00',
    rxRequired: false,
    inStock: true,
    delivery: '12-min Delivery',
    manufacturingDate: '15 January 2025',
    expiryDate: '14 January 2028',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCk-_EpEQLFht2CKhtb0jeeZWqy1hxBnuXWItblgDNLiopopa_ehLLraSMJ36Ssuq0HW_X_S5CZKbquhM14LKcpQNexaIJE6CPDfU9gE7EOcbjSTHmbKt9hoKWdTmhhjfOBaoxDL6JO2wMz1ej8KpI2mYHl3OluU6sRs5xX0OEru8Qntvsc2q86UV5SUGx5bhqMN-G2wY-iIU4LaW2mjNBhPpjAZXZa2Mkx4g1Xm8roqD6Tx4kB_NcaxA',
    uses: 'Used to treat mild to moderate pain and reduce fever. Commonly recommended for headaches, muscle aches, arthritis, backache, toothaches, colds, and fevers.',
    dosage: 'Take 500mg to 1000mg every 4 to 6 hours as needed. Do not exceed 4000mg in 24 hours. Take with a full glass of water. May be taken with or without food.',
    sideEffects: 'Generally well tolerated. Rare side effects may include nausea, stomach pain, or allergic reactions. Seek medical help if you notice rash, itching, or swelling.'
  },
  'amoxicillin-250mg': {
    name: 'Amoxicillin 250mg',
    generic: 'Amoxicillin Trihydrate',
    manufacturer: 'Cipla Ltd.',
    price: '₹1,035.00',
    rxRequired: true,
    inStock: true,
    delivery: '15-min Delivery',
    manufacturingDate: '08 March 2025',
    expiryDate: '07 March 2027',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAykQMNsxYZj46ZpttuVNgM-7j1Ncz7OhziVp1rGCmOb-jGFSViS7yedknfPjbrtoUoRFPiZMqE5tWO1NwUgDQQw-qlSyZsMwT8-TnnQFUvBSNatsq4lp-PZ4VW-HlIuvX1B2VhISIPzXXqKCFIo4IRCs0WgltcIOxSq1uXYdV3epwVmEpd_SfrcoN4fV3V7mFQc0LjGxhwIDwayle0rda3Gs25yIeEzYqSoIUUzov5dSQMoz0RewbCcg',
    uses: 'Used to treat bacterial infections such as pneumonia, bronchitis, and infections of the ears, nose, throat, urinary tract, and skin. It works by stopping the growth of bacteria.',
    dosage: 'Take this medication by mouth with or without food as directed by your doctor, usually every 8 or 12 hours. The dosage is based on your medical condition and response to treatment.',
    sideEffects: 'Common side effects include nausea, vomiting, or diarrhea. If any of these effects last or get worse, tell your doctor promptly.'
  },
  'amoxicillin-500mg': {
    name: 'Amoxicillin 500mg',
    generic: 'Amoxicillin Trihydrate',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals',
    price: '₹1,210.00',
    rxRequired: true,
    inStock: true,
    delivery: '15-min Delivery',
    manufacturingDate: '22 February 2025',
    expiryDate: '21 February 2028',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA9gvhZPebcbwA57i99_oPV0HR6HKMqID6X-tvfo4dVFJVtnxBLFn683dk-zXaGxvJQ8VAeGl5Bd41vzZLa5wPL04YwVcbh0fpfUOzvHSWHTNlSXdzQNwSpN0kXUq6nkQ4K88eNmMz1jHcnonGfTIqpqqNq_24FXBGs3wLAy4G8YVa4no-nuXSRUN1vKjS8MJCFNLseRf8vGLVBTVS4NdnLeYtZ1jp9-Mi3gtpuMToID8CZ1rp9s92mng',
    uses: 'Used to treat bacterial infections such as pneumonia, bronchitis, and infections of the ears, nose, throat, urinary tract, and skin. It works by stopping the growth of bacteria. It will not work for viral infections.',
    dosage: 'Take this medication by mouth with or without food as directed by your doctor, usually every 8 or 12 hours. The dosage is based on your medical condition and response to treatment.',
    sideEffects: 'Common side effects include nausea, vomiting, or diarrhea. If any of these effects last or get worse, tell your doctor promptly.'
  },
  'ibuprofen-syrup': {
    name: 'Ibuprofen Syrup',
    generic: 'Ibuprofen Oral Suspension',
    manufacturer: 'Dr. Reddy\'s Laboratories',
    price: '₹745.00',
    rxRequired: false,
    inStock: true,
    delivery: '15-min Delivery',
    manufacturingDate: '10 April 2025',
    expiryDate: '09 April 2027',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAslLhuLm6VB3zSjl0HqIHkOH5wWgSrm8fV4Tpsww17brUzV0JFuwXmLQmk6dUw9TBiWhwDETli4IXXr1lTWPdu4p8-n_pkfjM0brzHf8ZbnFGjlhugd9r1dJDXqwxu3RG5-wwSAIUQYBjeuPcfRQY7r3D9B2cmeEXznrUtY7DEg3taQkP6vAH6iUSzbcr-zm_-fXdRBN6RPGl8pEOS_JAKUrcgnp0aduZf5gf7V-iAjDcnhP_Lc3OfA',
    uses: 'Used to relieve pain from headaches, dental pain, menstrual cramps, muscle aches, and arthritis. Also reduces fever in children and adults.',
    dosage: 'Shake well before use. Take the prescribed dose using the measuring cup provided. Usually taken every 6 to 8 hours with food or milk to reduce stomach upset.',
    sideEffects: 'May cause stomach upset, nausea, or dizziness. Stop use and consult a doctor if you experience black stools, persistent stomach pain, or signs of allergic reaction.'
  },
  'cetirizine-10mg': {
    name: 'Cetirizine 10mg',
    generic: 'Cetirizine Hydrochloride',
    manufacturer: 'Zydus Healthcare',
    price: '₹543.00',
    rxRequired: false,
    inStock: true,
    delivery: '10-min Delivery',
    manufacturingDate: '05 December 2024',
    expiryDate: '04 December 2027',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2-gy135b_55x0fgpSkXezByFMnxgenVEwtPvmStD2trKWpQ0FUTi2Q8ICZBgCRMvdoS6qQYhAsdaBnqE2W9TZCtEn5CQTF8JnTg79EFDBoyHZGMR8j8aiuTRVmZPofqHXqWoZVVyMW0T_-1nW8DegAhwtUTLS5NLC6EVnczm3EB401gwaIT5zjOyhRpLrXYEteHXLm_aODTLImlfLcUpMqrlWTp4c7w9yGshWqHTFLQKI7yDEQ6aJeQ',
    uses: 'Provides effective relief from runny nose, sneezing, itchy or watery eyes, and itching of the nose or throat due to hay fever or other upper respiratory allergies.',
    dosage: 'Take one tablet once daily, preferably in the evening. May be taken with or without food. Do not exceed the recommended dose without medical advice.',
    sideEffects: 'Common side effects include drowsiness, dry mouth, and fatigue. Avoid driving or operating machinery if you feel sleepy after taking this medicine.'
  },
  'diclofenac-gel': {
    name: 'Diclofenac Gel',
    generic: 'Diclofenac Diethylamine',
    manufacturer: 'Novartis India',
    price: '₹480.00',
    rxRequired: false,
    inStock: true,
    delivery: '12-min Delivery',
    manufacturingDate: '18 June 2025',
    expiryDate: '17 June 2028',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCr-2VbdKlN-TU9JOQo77alRtl7EK4vteDkQ2u54WefKohRs2L9Fo5LeJDIxyebvc35nZzHgu2mrCtORSUDHU9t8_Bfh5KTLC5kK0nbt0LXYkbK2weK3SovKLkQiLkS6VhqHFGfdMJc1Oc-lLZCg8VRTpVKN512BaNGEo17uuwUukB-B5Rhmwx6bGu5IR43HSYBtRFoSqirPyGS9oB7bzC5NmsHBSVLO5mgHQu_MzqpPnvfbfGN86hzhQ',
    uses: 'Used for local relief of pain and inflammation in muscles, joints, and soft tissues. Suitable for sprains, strains, back pain, and sports injuries.',
    dosage: 'Apply a thin layer to the affected area 3 to 4 times daily. Gently rub in until absorbed. Wash hands after application unless treating the hands.',
    sideEffects: 'Local skin irritation, redness, or itching at the application site may occur. Discontinue use if severe rash or swelling develops.'
  },
  'azithromycin-500mg': {
    name: 'Azithromycin 500mg',
    generic: 'Azithromycin Dihydrate',
    manufacturer: 'Pfizer Ltd.',
    price: '₹769.00',
    rxRequired: true,
    inStock: true,
    delivery: '15-min Delivery',
    manufacturingDate: '12 May 2025',
    expiryDate: '11 May 2027',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDMCE4AG3T4GKQIOXDI4qQhFMgwsx-bns0Ip8RBpQEXaKWFzGdDqsRy8G8bvJa_iDnPvi9S9sWhhKNH3urpyPdwxSOncwl36yY7b0Ug9RcumXZx_ctFiDc0qutWSAkqTS8s9JeBE0Y7bnZnFiZ9q6gO-v3b4Qcrqq1zUc9EN_uWQ6N-5_AREt15UYCc5SR9F3kYklwhO0V0LRz5Ev9zCPzFCZ9_PyfMyPLE76zbi28S3vzlejrMKMO0eQ',
    uses: 'Used to treat a wide variety of bacterial infections including respiratory tract infections, skin infections, and sexually transmitted diseases.',
    dosage: 'Usually taken once daily as directed by your physician. Complete the full prescribed course even if symptoms improve early.',
    sideEffects: 'May cause diarrhea, nausea, abdominal pain, or headache. Contact your doctor if you experience severe or persistent side effects.'
  },
  'ciprofloxacin-500mg': {
    name: 'Ciprofloxacin 500mg',
    generic: 'Ciprofloxacin Hydrochloride',
    manufacturer: 'Bayer Pharmaceuticals',
    price: '₹1,537.00',
    rxRequired: true,
    inStock: true,
    delivery: '15-min Delivery',
    manufacturingDate: '03 January 2025',
    expiryDate: '02 January 2028',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9-m6fHKjF6tF7YbbZxtPYabNMmhwcatOKxipYA05xYu4Fdag9Fy5Fl9lsIC6l7dZFMmwMw1OeYkdNxcwIoiv82rgfrP7iyLcDtplPzCVg1hnGAEyuUvsWyCa3fz7fGEFoesWQchUk6-UuvtIMmAcwns2cF0gVG-s1Tf983fSiuOu-gTaexwqnZkZBVtrwdiyescI4A0VWCud6DoIpLr2Y4blcIYghrG3cMYRvDj4TUoeHU4UOWeCODg',
    uses: 'Treats bacterial infections of the urinary tract, respiratory system, skin, and gastrointestinal tract. Belongs to the fluoroquinolone class of antibiotics.',
    dosage: 'Take every 12 hours with a full glass of water. Avoid taking with dairy products or calcium-fortified juices close to dosing time.',
    sideEffects: 'Possible side effects include nausea, diarrhea, dizziness, and sensitivity to sunlight. Report tendon pain or swelling immediately.'
  },
  'doxycycline-100mg': {
    name: 'Doxycycline 100mg',
    generic: 'Doxycycline Hyclate',
    manufacturer: 'Abbott Healthcare',
    price: '₹1,011.00',
    rxRequired: true,
    inStock: true,
    delivery: '15-min Delivery',
    manufacturingDate: '28 November 2024',
    expiryDate: '27 November 2027',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQqdan83cjTBzzW7fVI-v8yTdkVTle8mqiqh4Ql_0aYTux0_LYxgQbhO1REJ9LkGRpsr5YyrZswVA5imb1i7eT2Cee5UYjGvNKXmxK2rw7mE_5bh4BLj3FToyyIiS1pZ8vfgIGCxAayRCSylCZD07L8QRnd4USYZhOJeDep4HjYkLkmh8nfAdT_ZMzH0PxGGzhx6KDKKvi5Zs0VOBSrJwkSSlXxDlJ0kyT2aKD5Rmungv3KZENIgrHkg',
    uses: 'Used for respiratory tract infections, acne, Lyme disease, and certain sexually transmitted infections. Also used for malaria prevention in some cases.',
    dosage: 'Take with a full glass of water while sitting or standing upright. Avoid lying down for at least 30 minutes after taking to prevent esophageal irritation.',
    sideEffects: 'May cause photosensitivity, nausea, or esophageal irritation. Use sun protection while taking this medication.'
  },
  'augmentin-625mg': {
    name: 'Augmentin 625mg',
    generic: 'Amoxicillin + Clavulanic Acid',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals',
    price: '₹1,838.00',
    rxRequired: true,
    inStock: true,
    delivery: '15-min Delivery',
    manufacturingDate: '14 September 2025',
    expiryDate: '13 September 2028',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQ3bM42cDgvIi-wWWGqP7lkHmE-IZANsja-sFIu2VBMR1zTR0FsJnCewsFmY6iZgY-OnejElcLnpOFsBpeTwEuwBzo_1RqsTxITaj6Kyhi-cDRG62g_9mVpEJFYoT9SScwtrgtJ-grDC4-7Dg0fS3bLfvGfOajcBAqiLEfqOAq7gRvEsjJIpqbyDLGCPFnqGEXbBcQrIMyLiYoqvwA3P1stHqnonNThbkodcbWQ17LMTEUxqABTEdGyg',
    uses: 'Combination antibiotic used for infections resistant to amoxicillin alone, including sinusitis, pneumonia, ear infections, and urinary tract infections.',
    dosage: 'Take at the start of a meal to reduce stomach upset. Complete the full course as prescribed by your doctor.',
    sideEffects: 'Diarrhea is more common with this combination. Report severe diarrhea, rash, or yellowing of the skin to your doctor promptly.'
  }
};
