tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "surface-tint": "#006e2d",
                      "on-tertiary": "#ffffff",
                      "surface-container-highest": "#d3e4fe",
                      "surface-bright": "#f8f9ff",
                      "on-secondary-fixed": "#002109",
                      "surface-container": "#e5eeff",
                      "outline-variant": "#bdcaba",
                      "on-primary-container": "#f7fff2",
                      "on-primary-fixed-variant": "#005320",
                      "tertiary-container": "#316bf3",
                      "inverse-primary": "#62df7d",
                      "on-surface": "#0b1c30",
                      "error-container": "#ffdad6",
                      "primary-container": "#00873a",
                      "primary-fixed": "#7ffc97",
                      "secondary-fixed": "#6bff8f",
                      "secondary": "#006e2f",
                      "on-secondary-container": "#007432",
                      "secondary-fixed-dim": "#4ae176",
                      "on-tertiary-fixed": "#00174b",
                      "inverse-on-surface": "#eaf1ff",
                      "on-primary-fixed": "#002109",
                      "tertiary": "#0051d5",
                      "outline": "#6e7b6c",
                      "on-error-container": "#93000a",
                      "background": "#f8f9ff",
                      "primary-fixed-dim": "#62df7d",
                      "on-tertiary-fixed-variant": "#003ea8",
                      "surface-container-high": "#dce9ff",
                      "surface-variant": "#d3e4fe",
                      "surface-container-low": "#eff4ff",
                      "surface-dim": "#cbdbf5",
                      "surface": "#f8f9ff",
                      "inverse-surface": "#213145",
                      "on-primary": "#ffffff",
                      "on-secondary": "#ffffff",
                      "surface-container-lowest": "#ffffff",
                      "on-tertiary-container": "#fefcff",
                      "tertiary-fixed-dim": "#b4c5ff",
                      "secondary-container": "#6bff8f",
                      "on-surface-variant": "#3e4a3d",
                      "tertiary-fixed": "#dbe1ff",
                      "on-error": "#ffffff",
                      "on-background": "#0b1c30",
                      "primary": "#006b2c",
                      "on-secondary-fixed-variant": "#005321",
                      "error": "#ba1a1a"
              },
              "borderRadius": {
                      "DEFAULT": "0.25rem",
                      "lg": "0.5rem",
                      "xl": "0.75rem",
                      "full": "9999px"
              },
              "spacing": {
                      "gutter": "16px",
                      "container-margin-desktop": "48px",
                      "sm": "8px",
                      "lg": "24px",
                      "xs": "4px",
                      "xl": "32px",
                      "container-margin-mobile": "16px",
                      "unit": "4px",
                      "md": "16px"
              },
              "fontFamily": {
                      "h1": ["Geist"],
                      "h2": ["Geist"],
                      "h3": ["Geist"],
                      "body-md": ["Geist"],
                      "display": ["Geist"],
                      "caption": ["Geist"]
              },
              "fontSize": {
                      "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                      "h2": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                      "h3": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                      "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                      "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                      "h1-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                      "h2-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                      "caption": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}]
              }
            },
          },
        }
