tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface-container-high": "#dce9ff",
                    "inverse-surface": "#213145",
                    "tertiary-fixed": "#dbe1ff",
                    "error": "#ba1a1a",
                    "surface-container-highest": "#d3e4fe",
                    "on-primary-container": "#f7fff2",
                    "background": "#f8f9ff",
                    "surface-variant": "#d3e4fe",
                    "on-primary-fixed": "#002109",
                    "on-background": "#0b1c30",
                    "outline-variant": "#bdcaba",
                    "surface-container-lowest": "#ffffff",
                    "surface-bright": "#f8f9ff",
                    "primary-fixed": "#7ffc97",
                    "tertiary-fixed-dim": "#b4c5ff",
                    "on-error-container": "#93000a",
                    "secondary-container": "#6bff8f",
                    "surface-dim": "#cbdbf5",
                    "secondary-fixed": "#6bff8f",
                    "on-tertiary": "#ffffff",
                    "on-primary-fixed-variant": "#005320",
                    "on-surface-variant": "#3e4a3d",
                    "error-container": "#ffdad6",
                    "surface": "#f8f9ff",
                    "on-secondary-container": "#007432",
                    "secondary": "#006e2f",
                    "primary-container": "#00873a",
                    "on-surface": "#0b1c30",
                    "on-tertiary-fixed-variant": "#003ea8",
                    "on-secondary": "#ffffff",
                    "tertiary": "#0051d5",
                    "inverse-on-surface": "#eaf1ff",
                    "primary": "#006b2c",
                    "tertiary-container": "#316bf3",
                    "surface-tint": "#006e2d",
                    "on-tertiary-fixed": "#00174b",
                    "outline": "#6e7b6c",
                    "inverse-primary": "#62df7d",
                    "on-secondary-fixed": "#002109",
                    "secondary-fixed-dim": "#4ae176",
                    "primary-fixed-dim": "#62df7d",
                    "on-secondary-fixed-variant": "#005321",
                    "on-tertiary-container": "#fefcff",
                    "on-error": "#ffffff",
                    "surface-container-low": "#eff4ff",
                    "on-primary": "#ffffff",
                    "surface-container": "#e5eeff"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "gutter": "16px",
                    "xs": "4px",
                    "unit": "4px",
                    "md": "16px",
                    "container-margin-desktop": "48px",
                    "xl": "32px",
                    "lg": "24px",
                    "sm": "8px",
                    "container-margin-mobile": "16px"
            },
            "fontFamily": {
                    "helper": ["Geist"],
                    "h2": ["Geist"],
                    "caption": ["Geist"],
                    "body-lg": ["Geist"],
                    "body-sm": ["Geist"],
                    "h3": ["Geist"],
                    "h1-mobile": ["Geist"],
                    "h1": ["Geist"],
                    "body-md": ["Geist"],
                    "display": ["Geist"]
            },
            "fontSize": {
                    "helper": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
                    "h2": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                    "caption": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "h3": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                    "h1-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                    "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
            }
          },
        },
      }
