tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "surface-bright": "#f8f9ff",
                        "on-tertiary": "#ffffff",
                        "primary-container": "#00873a",
                        "primary-fixed": "#7ffc97",
                        "on-secondary-fixed-variant": "#005321",
                        "on-primary": "#ffffff",
                        "secondary-fixed-dim": "#4ae176",
                        "on-tertiary-fixed": "#00174b",
                        "secondary": "#006e2f",
                        "background": "#f8f9ff",
                        "on-surface": "#0b1c30",
                        "on-secondary": "#ffffff",
                        "tertiary-fixed-dim": "#b4c5ff",
                        "primary-fixed-dim": "#62df7d",
                        "error": "#ba1a1a",
                        "outline-variant": "#bdcaba",
                        "outline": "#6e7b6c",
                        "on-tertiary-fixed-variant": "#003ea8",
                        "on-primary-fixed-variant": "#005320",
                        "surface-variant": "#d3e4fe",
                        "surface": "#f8f9ff",
                        "surface-container-highest": "#d3e4fe",
                        "on-background": "#0b1c30",
                        "tertiary-fixed": "#dbe1ff",
                        "on-secondary-container": "#007432",
                        "surface-tint": "#006e2d",
                        "inverse-on-surface": "#eaf1ff",
                        "surface-dim": "#cbdbf5",
                        "surface-container-low": "#eff4ff",
                        "secondary-fixed": "#6bff8f",
                        "on-primary-container": "#f7fff2",
                        "surface-container-lowest": "#ffffff",
                        "secondary-container": "#6bff8f",
                        "tertiary-container": "#316bf3",
                        "primary": "#006b2c",
                        "on-tertiary-container": "#fefcff",
                        "tertiary": "#0051d5",
                        "on-secondary-fixed": "#002109",
                        "surface-container-high": "#dce9ff",
                        "on-error-container": "#93000a",
                        "error-container": "#ffdad6",
                        "on-error": "#ffffff",
                        "inverse-primary": "#62df7d",
                        "surface-container": "#e5eeff",
                        "on-surface-variant": "#3e4a3d",
                        "on-primary-fixed": "#002109",
                        "inverse-surface": "#213145"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "xs": "4px",
                        "gutter": "16px",
                        "xl": "32px",
                        "unit": "4px",
                        "sm": "8px",
                        "md": "16px",
                        "container-margin-mobile": "16px",
                        "lg": "24px",
                        "container-margin-desktop": "48px"
                    },
                    "fontFamily": {
                        "display": ["Geist"],
                        "h1": ["Geist"],
                        "h2": ["Geist"],
                        "h3": ["Geist"],
                        "body-lg": ["Geist"],
                        "body-md": ["Geist"],
                        "body-sm": ["Geist"],
                        "caption": ["Geist"],
                        "helper": ["Geist"]
                    }
                }
            }
        }
